### ISSUE TITLE
Examples request

### ISSUE THREAD

**Issue by lnacquaroli** [ngedwin98/ABCDBeamTrace.jl#1]
Hello, sorry to bother. I was wondering if you plan to release a working example for this to see how to use it. Thanks!

**Comment by ngedwin98** [comment]
Hello, and thanks for the interest! I've been wanting to write some informal documentation and examples for some time...since there's now a request, I'll see what I can put together by early next week.

**Comment by ngedwin98** [comment]
Informal documentation is up as of commit 092d978, from a few weeks back. I still have plans to put together a notebook or two going through a free-space cavity design and mode-matching calculations, but that will be more involved, and I'm still trying to find the time. In the meanwhile, do you have any feedback for whether the README helps at all in understanding this package? I am open to shaping the notebook tutorials (and editing the README) based on your interests and application.

**Comment by lnacquaroli** [comment]
This is great. With the README as it is looks useful enough. Thanks!
